# Generated by Django 5.1.1 on 2024-09-13 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='San',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('num_cuotas', models.PositiveIntegerField()),
                ('payment_frequency', models.CharField(choices=[('mensual', 'Mensual'), ('quincenal', 'Quincenal')], default='mensual', max_length=10)),
                ('cuota', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('type_of_san', models.CharField(choices=[('ahorro', 'Ahorro'), ('producto', 'Producto')], max_length=255)),
                ('image', models.ImageField(upload_to='products/')),
            ],
        ),
    ]
