# Generated by Django 5.1.1 on 2024-09-29 22:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sanes', '0003_san_fecha_inicio_san_organizador_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='cupo',
            name='comprobante_pago',
            field=models.ImageField(blank=True, null=True, upload_to='comprobantes/'),
        ),
        migrations.AddField(
            model_name='cupo',
            name='estado',
            field=models.CharField(choices=[('pendiente_confirmacion', 'Pendiente de Confirmación'), ('confirmado', 'Confirmado'), ('rechazado', 'Rechazado')], default='pendiente_confirmacion', max_length=30),
        ),
        migrations.AddField(
            model_name='cupo',
            name='metodo_pago',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='cupo',
            name='participante',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
