# Generated by Django 5.1.1 on 2024-09-30 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sanes', '0004_cupo_comprobante_pago_cupo_estado_cupo_metodo_pago_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='email',
            field=models.EmailField(default='default@example.com', max_length=254),
        ),
    ]
