# Generated by Django 5.1.1 on 2024-09-30 06:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sanes', '0005_userprofile_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='email',
        ),
    ]
