# Generated by Django 5.1.1 on 2024-09-30 08:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sanes', '0006_remove_userprofile_email'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Participacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_ultima_cuota', models.DateField(blank=True, null=True)),
                ('cuotas_pagadas', models.IntegerField(default=0)),
                ('san', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sanes.san')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
