# Generated by Django 5.1.1 on 2024-09-30 10:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sanes', '0008_pago'),
    ]

    operations = [
        migrations.AddField(
            model_name='pago',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('confirmado', 'Confirmado'), ('rechazado', 'Rechazado')], default='pendiente', max_length=30),
        ),
        migrations.AlterField(
            model_name='pago',
            name='cupo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sanes.cupo'),
        ),
        migrations.AlterField(
            model_name='pago',
            name='fecha_pago',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='pago',
            name='metodo_pago',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
