# Generated by Django 5.1.1 on 2024-09-30 12:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sanes', '0009_pago_estado_alter_pago_cupo_alter_pago_fecha_pago_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pago',
            name='order',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='sanes.order'),
        ),
    ]
